services:
  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    ports:
      - "9042:9042"  # Cassandra default port
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
    volumes:
      - cassandra-data:/var/lib/cassandra
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "SHOW HOST" ]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

  go-tutorial:
    image: go-tutorial  # Replace with the name of your Docker image
    container_name: go-tutorial
    build:
      context: .
    depends_on:
      cassandra:
        condition: service_healthy
    environment:
      - CASSANDRA_HOST=cassandra  # Name of the Cassandra service
      - CASSANDRA_PORT=9042
    ports:
      - "8080:8080"  # Replace with the port your Go app listens on


volumes:
  cassandra-data: